easy_notes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # Home page
    path('', include('easy_notes_app.urls')),
]

easy_notes_app/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 25 14:25:05 2021

@author: alina

Defines URL patterns for easy_notes_app.
"""

from django.urls import path
from . import views

app_name = "easy_notes_app"

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # About page
    path('about/', views.about, name='about'),
    # Page for adding a new note
    path('new_note/', views.new_note, name='new_note'),
    # Page for adding a new list
    path('new_list/', views.new_list, name='new_list'),
    # Board page
    path('notes/', views.notes, name='notes'),
    # Page to show a note
    path('note/<int:note_id>', views.note, name='note'),
    # Page for editing a note
    path('edit_note/<int:note_id>', views.edit_note, name='edit_note'),
    # Page to show a list
    # path('lista/<int:lista_id>', views.lista, name='lista'),
    ]

easy_notes_app/models.py
from django.db import models


class Note(models.Model):
    """A basic sticky note."""
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.title) > 30:
            return self.title[:30] + "..."
        else:
            return self.title


class ToDoList(models.Model):
    """A checklist note."""
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    text_01 = models.CharField(max_length=100, blank=True)
    text_02 = models.CharField(max_length=100, blank=True)
    text_03 = models.CharField(max_length=100, blank=True)
    text_04 = models.CharField(max_length=100, blank=True)
    text_05 = models.CharField(max_length=100, blank=True)
    text_06 = models.CharField(max_length=100, blank=True)
    text_07 = models.CharField(max_length=100, blank=True)
    text_08 = models.CharField(max_length=100, blank=True)
    text_09 = models.CharField(max_length=100, blank=True)
    text_10 = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.title) > 30:
            return self.title[:30] + "..."
        else:
            return self.title

easy_notes_app/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 30 09:32:51 2021

@author: alina
"""

from django import forms

from .models import Note, ToDoList

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title',
                  'text',
                  ]
        labels = {'title': 'Title',
                  'text': '',
                  }
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class ToDoListForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ['title',
                  'text_01',
                  'text_02',
                  'text_03',
                  'text_04',
                  'text_05',
                  'text_06',
                  'text_07',
                  'text_08',
                  'text_09',
                  'text_10',
                  ]
        labels = {'Give your list a title': '',
                  'Enter your items here': '',
                  }

easy_notes_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import NoteForm, ToDoListForm
from .models import Note, ToDoList

def index(request):
    """The home page for Easy Notes."""
    return render(request, 'easy_notes_app/index.html')


def about(request):
    """The about page for Easy Notes."""
    return render(request, 'easy_notes_app/about.html')



def notes(request): # was 'board'
    """The board were all Easy Notes are displayed."""
    notes = Note.objects.order_by('date_added')
    #lists = ToDoList.objects.order_by('date_added')
    context = {'notes': notes,
               #'lists': lists,
               }
    return render(request, 'easy_notes_app/notes.html', context)


def note(request, note_id):
    """Show a single note."""
    note = Note.objects.get(id=note_id)
    context = {'note': note}
    return render(request, 'easy_notes_app/note.html', context) 


# def lista(request, lista_id):
#     """Show a single list."""
#     lista = ToDoList.objects.get(id=lista_id)
#     context = {'lista': lista}
#     return render(request, 'easy_notes_app/lista.html', context) 



def new_note(request):
    """Add a new note."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = NoteForm()
    else:
        # POST data submitted; process data.
        form = NoteForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('easy_notes_app:notes')) # board doesn't exist yet!!!
    context = {'form': form}
    return render(request, 'easy_notes_app/new_note.html', context)


def new_list(request):
    """Add a new list."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = ToDoListForm()
    else:
        # POST data submitted; process data.
        form = ToDoListForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('easy_notes_app:notes')) # board doesn't exist yet!!!
    context = {'form': form}
    return render(request, 'easy_notes_app/new_list.html', context)


def edit_note(request, note_id):
    """Edit an existing note."""
    
    entry = Note.objects.get(id=note_id)
    
    if request.method != 'POST':
        # Initial request; pre-fillform with the current entry.
        form = NoteForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = NoteForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('easy_notes_app:notes')
    
    context = {'entry': entry,
                'form': form}
    return render(request, 'easy_notes_app/edit_note.html', context)

easy_notes_app/templates/easy_notes_app/about.html
{% extends "easy_notes_app/base.html" %}

{% block content %}

  {% load static %}
  <!--First section-->
  <div class="container col-xxl-8 px-4 py-5">
  	<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
  		<div class="col-10 col-sm-8 col-lg-6">
              <img src="{% static 'easy_notes_app/jesus-hilario-h-5v69Vl62NCM-unsplash.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Messy desktop" loading="lazy">
  		</div>
  		<div class="col-lg-6">
  			<div class="lc-block mb-3">
  				<div editable="rich">
  					<h2 class="fw-bold display-5">Easy Notes helps you to manage your work area, so you can go from this...</h2>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
  <!--First section-->
  <!--Second section-->
  <div class="container col-xxl-8 px-4 py-5">
  	<div class="row flex-lg-row-reverse align-items-center g-5 py-5">
  		<div class="col-10 col-sm-8 col-lg-6">
              <img src="{% static 'easy_notes_app/jeff-sheldon-mKxdiW2QEkE-unsplash.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Tidy desktop" loading="lazy">
  		</div>
  		<div class="col-lg-6">
  			<div class="lc-block mb-3">
  				<div editable="rich">
  					<h2 class="fw-bold display-5">...to something more like this:</h2>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
  <!--Second section-->
  <!--Third section-->
  <div class="container-fluid px-4 py-5 my-5 text-center">
  	<div class="lc-block d-block mx-auto mb-4">

  		{% load static %}    
        <img src="{% static 'easy_notes_app/leave-clutter-behind.png' %}"
             alt="Walking with backpack in a cactus shop"
             weight='300'
             height='225'>
  	</div>
  	<div class="lc-block">
  		<div editable="rich">
  
  			<h2 class="display-5 fw-bold">EasyNotes is a web-based sticky notes tool that lets you easily add notes on a digital board.</h2>
  
  		</div>
  	</div>
  	<div class="lc-block col-lg-6 mx-auto mb-4">
  		<div editable="rich">
  			<p class="lead ">
              Give a title to your notes, write them as just text or as a to-do list.
              It keeps all your notes listed so you can quickly see the contents of each one and find the one you want.</p>
            <p class="lead ">
              Incorporate EasyNotes into your workflow for study or work, keep all your notes organized in one virtual board
              and take them with you wherever you go. Leave all clutter behind.</p>
  		</div>
  	</div>
  
  	<div class="lc-block d-grid gap-2 d-sm-flex justify-content-sm-center"> <a class="btn btn-primary btn-lg px-4 gap-3" href="{% url 'easy_notes_app:notes' %}" role="button">Go to your board</a>
  		<a class="btn btn-outline-secondary btn-lg px-4" href="{% url 'easy_notes_app:index' %}" role="button">Home</a>
  	</div>
  </div>
  <!--Third section-->
  <div class="text-left">
    <div class="container p-4 pb-0">
      <!-- Section: Credits -->
      <section class="mb-4 text-left icons">
        <div class="icons">
          <p>
            Icons made by: <a href="https://www.freepik.com" title="Freepik">Freepik</a>: <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> |
              <a href="https://www.flaticon.com/authors/google" title="Google">Google</a>: <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>    
          </p>
          <p>
            Photos by: <a href="https://unsplash.com/@freegraphictoday?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">AbsolutVision</a>: <a href="https://unsplash.com/?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a> | 
            <a href="https://unsplash.com/@jesushilarioh?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jesus Hilario H.</a>: <a href="https://unsplash.com/s/photos/messy-desktop?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a> | 
            <a href="https://unsplash.com/@ugmonk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Jeff Sheldon</a>: <a href="https://unsplash.com/s/photos/tidy-desk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a> |
            <a href="https://unsplash.com/@kylejglenn?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Kyle Glenn</a>: <a href="https://unsplash.com/s/photos/sticky-notes?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a> |
            <a href="https://unsplash.com/@leoniechristine_visuals?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Leonie Christine</a>: <a href="https://unsplash.com/s/photos/walking-city-backpack?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
          </p>
        </div>
      </section>
    </div>
  </div>
{% endblock content %}

easy_notes_app/templates/easy_notes_app/base.html
<!DOCTYPE html>
<html lang="eng-us">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

      
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@300&family=Raleway&display=swap" rel="stylesheet"> 
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'easy_notes_app/base-styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/sticky-notes.png' %}"/>
        
    {% if title %}
        <title>Easy Notes - {{ title }}</title>
    {% else %}
        <title>Easy Notes - Your notes go with you</title>
    {% endif %}
  
  </head>
  <body>
  <!-- Navbar -->
    <nav class="navbar navbar-dark bg-dark">
      <!-- Navbar content -->
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'easy_notes_app:index' %}">Easy Notes</a>
      </div>
    </nav>
  <!-- Navbar -->
  
  {% block content %}{% endblock content %}
  
  <!-- Footer -->
  <footer class="bg-dark text-center text-white">
    {% load static %}
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4 text-center">
        <!-- Linkedin -->
        <a class="btn btn-floating m-1"
           href="https://www.linkedin.com/in/alina-sansevich-070b6159/"
           role="button">
           <img src="{% static 'easy_notes_app/white-linkedin-icon-text-label-symbol-number-transparent-png-2024887.png' %}" alt="LinkedIn logo" width="32" height="32">
           </a>
        <!-- Github -->
        <a class="btn btn-floating m-1"
           href="https://github.com/alinasansevich/easy-notes"
           role="button">
           <img src="{% static 'easy_notes_app/GitHub-Mark-Light-32px.png' %}" alt="GitHub Mark Light">
           </a>
      </section>
    <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
      <div class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)">© 2021 Copyright:
        <a class="text-white copyright" href="https://github.com/alinasansevich/easy-notes"
           >Alina Sansevich | MIT License</a>
      </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

    <!-- Optional JavaScript; Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
  </body>
</html>

easy_notes_app/templates/easy_notes_app/board.html
{% extends "easy_notes_app/base.html" %}

{% block content %}

 
  <h3>I'm still figuring out this one :)</h3>

  
{% endblock content %}

easy_notes_app/templates/easy_notes_app/edit_note.html
{% extends "easy_notes_app/base.html" %}

{% block content %}

  <h3>Edit note:</h3>

    <form action="{% url 'easy_notes_app:edit_note' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }} <!-- 'as_p' modifier: all form elements will be rendered in paragraph format  -->

      <button type="button" class="btn btn-primary" name="submit">Save Changes</button>
      <a href="{% url 'easy_notes_app:notes' %}">Go back</a>
    </form>
        
{% endblock content %}

easy_notes_app/templates/easy_notes_app/index.html
{% extends "easy_notes_app/base.html" %}

{% block content %}
  <div class="container my-5">
  	<div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
  		<div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
  			<div class="lc-block mb-3">
  				<div editable="rich">
  					<h2 class="fw-bold display-4">Easy Notes&nbsp;<p></p>
  						<h3>Your notes go with you.</h3>
  					</h2>
  				</div>
  			</div>
  
  			<div class="lc-block mb-3">
  				<div editable="rich">
  					<p class="lead">Tidy up your workspace<br>
                        Notes, to-do lists, reminders...<br>
                        Manage your workspace easily<br>
                        No more clutter in your fridge!<br>                      
  					</p>
  				</div>
  			</div>
  
  			<div class="lc-block d-grid gap-2 d-md-flex justify-content-md-start"><a class="btn btn-primary px-4 me-md-2" href="{% url 'easy_notes_app:notes' %}" role="button">Go to your board</a>
  				<a class="btn btn-outline-secondary px-4" href="{% url 'easy_notes_app:about' %}" role="button">About this app</a>
  			</div>
  		</div>
  		<div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
  			<div class="lc-block">
  			{% load static %}	
              <img src="{% static 'easy_notes_app/absolutvision-82TpEld0_e4-unsplash.jpg' %}"
                   alt="Idea note pined on a board."
                   weight='500'
                   height='375'>
            </div>
  		</div>
  	</div>
  </div>
{% endblock content %}

easy_notes_app/templates/easy_notes_app/lista.html
{% extends "easy_notes_app/base.html" %}

{% block content %}
  
  <p>Note: {{ lista.title }}</p> <!-- {{ topic }} is a "template variable", and it's available because it's in the context dict, from views.topic -->
  
  <p>{{ lista.date_added|date:'M d, Y H:i' }}</p>
  
  <ul>
    {% for item in lista %}
    <li>
      <a href="{% url 'easy_notes_app:lista' lista.id %}">{{ item }}</a>
    </li>
    {% endfor %}
  </ul>  
  <!-- <p><a href="{% url 'easy_notes_app:edit_lista' note.id %}">edit list</a></p> -->
  <div>
    <a href="{% url 'easy_notes_app:index' %}">Home</a>
  </div>

{% endblock content %}


<!-- lista, a ToDoList object, is not iterable
     I need to rethink all this part of the project -->

easy_notes_app/templates/easy_notes_app/new_list.html
{% extends "easy_notes_app/base.html" %}

{% block content %}

 
  <h3>Add a new list:</h3>

    <form action="{% url 'easy_notes_app:new_list' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }} <!-- 'as_p' modifier: all form elements will be rendered in paragraph format  -->
      <button name="submit">add new list</button>
    </form>

  
{% endblock content %}

easy_notes_app/templates/easy_notes_app/new_note.html
{% extends "easy_notes_app/base.html" %}

{% block content %}

 
  <h3>Add a new note:</h3>

    <form action="{% url 'easy_notes_app:new_note' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }} <!-- 'as_p' modifier: all form elements will be rendered in paragraph format  -->
      <button name="submit">add new note</button>
      <a href="{% url 'easy_notes_app:notes' %}">Go back</a>
    </form>

  
{% endblock content %}

easy_notes_app/templates/easy_notes_app/note.html
{% extends "easy_notes_app/base.html" %}

{% block content %}
  
  <p>Note: {{ note.title }}</p> <!-- {{ topic }} is a "template variable", and it's available because it's in the context dict, from views.topic -->
  
  <p>{{ note.date_added|date:'M d, Y H:i' }}</p>
  <p>{{ note.text|linebreaks }}</p>
  <p><a href="{% url 'easy_notes_app:edit_note' note.id %}">edit note</a></p>
  
  <div>
    
    <a href="{% url 'easy_notes_app:notes' %}">Go back</a>
    <a href="{% url 'easy_notes_app:index' %}">Home</a>
  </div>

  
{% endblock content %}

easy_notes_app/templates/easy_notes_app/notes.html
{% extends "easy_notes_app/base.html" %}

{% block content %}
    
    <h2>Notes:</h2>
    
    <ul>
    {% for note in notes %}
        <li>
          <a href="{% url 'easy_notes_app:note' note.id %}">{{ note }}</a>
          <a href="{% url 'easy_notes_app:edit_note' note.id %}">Edit</a>
        </li>
    {% empty %}
        <li>No notes have been added yet.</li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'easy_notes_app:new_note' %}">Add a new note:</a>
    
            
{% endblock content %}